version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5333:5432"
    environment:
      POSTGRES_PASSWORD: nika
      POSTGRES_USER: nika
      POSTGRES_DB: nika