version: '3.1'

services:
  strapi:
    build:
      context: ./strapi
    environment:
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - LOGIN=${LOGIN}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGE_DIR=${IMAGE_DIR}
      - UPLOADS_DIR=${UPLOADS_DIR}
    ports:
      - 8000:${PORT}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
  client:
    build:
      context: ./client
    ports:
      - 8081:8080
    depends_on:
      - strapi
    restart: unless-stopped
