version: '3.1'

services:
  strapi:
    build:
      context: ./strapi
    image: valentinalekhin/nikadmitrieva-server
    ports:
      - "1337:1337"
    volumes:
      - ./.cache:/home/app/.cache
      - ./.tmp:/home/app/.tmp
    restart: unless-stopped
  client:
    build:
      context: ./client
    image: valentinalekhin/nikadmitrieva-client
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    restart: unless-stopped
