version: '3.5'

services:
  strapi:
    build:
      context: ./strapi
    image: valentinalekhin/nikadmitrieva-server
    container_name: strapi
    hostname: strapi
    ports:
      - "1337:1337"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - STRAPI_URL=${STRAPI_URL}
    volumes:
      - ./.cache:/app/.cache
      - ./.tmp:/app/.tmp
      - ./public:/app/public
    networks:
      - default
    restart: unless-stopped
  client:
    build:
      context: ./client
    image: valentinalekhin/nikadmitrieva-client
    container_name: client
    hostname: client
    ports:
      - "3000:3000"
    environment:
      - BASE_URL='http://starpi:1337'
    networks:
      - default
    depends_on:
      - strapi
    restart: unless-stopped

networks:
  default:
