version: '3.1'

services:
  server:
    build:
      context: ./server
    environment:
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - LOGIN=${LOGIN}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGE_DIR=${IMAGE_DIR}
      - UPLOADS_DIR=${UPLOADS_DIR}
    ports:
      - 8000:${PORT}
    volumes:
      - ./data:/app/data
    restart: always
  admin:
    build:
      context: ./admin
    depends_on:
      - server
    environment:
      - VUE_APP_BASE_URL=${VUE_APP_BASE_URL}
    ports:
      - 8080:8080
    restart: always
  client:
    build:
      context: ./client
    ports:
      - 8081:8080
    depends_on:
      - server
      - admin
    restart: always
