version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5333:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
  strapi:
    build:
      context: ../../strapi
    image: valentinalekhin/nikadmitrieva-server
    container_name: strapi
    hostname: strapi
    ports:
      - "1337:1337"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - STRAPI_URL=${STRAPI_URL}
      - BUILDER_KEY=${BUILDER_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./.cache:/app/.cache
      - ./.tmp:/app/.tmp
      - ./public:/app/public
    networks:
      - default
    restart: unless-stopped
  client:
    build:
      context: ../../client
    image: valentinalekhin/nikadmitrieva-client
    container_name: client
    hostname: client
    volumes:
      - ./dist:/home/app/dist
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=https://api.nikadmitrieva.ru
      - BUILDER_KEY=${BUILDER_KEY}
    networks:
      - default
    depends_on:
      - strapi
    restart: unless-stopped

networks:
  default:
