version: '3.5'

services:
  db:
    image: postgres:14-alpine
    container_name: nikadmitrieva-database
    restart: unless-stopped
    ports:
      - "5005:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  strapi:
    build:
      context: ../../strapi
    image: valentinalekhin/nikadmitrieva-server
    container_name: nikadmitrieva-strapi
    hostname: strapi
    ports:
      - "1337:1337"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - STRAPI_URL=${STRAPI_URL}
      - BUILDER_KEY=${BUILDER_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - cache:/app/.cache
      - tmp:/app/.tmp
      - public:/app/public
      - uploads:/app/public/uploads
    networks:
      - default
    restart: unless-stopped

  client:
    build:
      context: ../../client
    image: valentinalekhin/nikadmitrieva-client
    container_name: nikadmitrieva-client
    hostname: client
    volumes:
      - client:/home/app/dist
    environment:
      - BASE_URL=http://strapi:1337
      - BUILDER_KEY=${BUILDER_KEY}
    networks:
      - default
    depends_on:
      - strapi
    restart: unless-stopped

  web:
    image: valentinalekhin/nikadmitrieva-web
    container_name: nikadmitrieva-web
    build:
      context: ../../web
    ports:
      - "3005:80"
    volumes:
      - client:/var/www/client:ro
      - uploads:/var/www/uploads:ro
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - client

volumes:
  db-data:
  client:
  cache:
  tmp:
  public:
  uploads:

networks:
  default:
